# Generated by Django 5.0.6 on 2025-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_alter_goal_updated_at_cart_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerhiring',
            name='time_slot',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
